version: 2
before:
  hooks:
    - ./scripts/build-static-ci-windows-amd64.sh
builds:
  - env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -linkmode 'external' -extldflags '-static -lntdll -lsetupapi'
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
checksum:
  disable: true
