---
version: 2

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
#      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
