version: 2
before:
  hooks:
    - ./scripts/build-dynamic-ci-darwin-arm64.sh
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
checksum:
  disable: true