version: 2
env:
  - TARGET=armv7-unknown-linux-gnueabihf
before:
  hooks:
    - ./scripts/build-static-ci.sh
builds:
  - env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    goos:
      - linux
    goarch:
      - arm
    ldflags:
      - -linkmode 'external' -extldflags '-static'
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
checksum:
  disable: true
