version: 2
before:
  hooks:
    - ./scripts/build-static-ci-linux-arm64.sh
builds:
  - env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-musl-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -linkmode 'external' -extldflags '-static'
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
checksum:
  disable: true
