version: 2
before:
  hooks:
    - ./scripts/build-dynamic-ci-linux-amd64.sh
builds:
  - env:
      - CGO_ENABLED=1
      - CC=gcc
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
checksum:
  disable: true