version: 2
before:
  hooks:
    - ./scripts/build-static-ci-linux-arm64.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -extldflags "-static"
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
    flags:
      - -a
      - -installsuffix cgo
checksum:
  disable: true
