version: 2
env:
  - TARGET=x86_64-unknown-linux-gnu
before:
  hooks:
    - ./scripts/build-static-ci.sh
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -linkmode 'external' -extldflags '-static'
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
checksum:
  disable: true
