version: 2
env:
  - TARGET=aarch64-unknown-linux-gnu
before:
  hooks:
    - ./scripts/build-static-ci.sh
builds:
  - env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -linkmode 'external' -extldflags '-static'
      - -w -s
      - -X github.com/kahnwong/swissknife/cmd.version={{.Version}}
checksum:
  disable: true
