#!/bin/bash

case "$(uname -s)" in
    Linux*)     OS="linux";;
    Darwin*)    OS="darwin";;
    CYGWIN*|MINGW*|MSYS*) OS="windows";;
    *)          OS="unknown";;
esac

# detect architecture
case "$(uname -m)" in
    x86_64)    ARCH="amd64";;
    aarch64)   ARCH="arm64";;
    arm64)     ARCH="arm64";;
    *)         ARCH="unknown";;
esac

REPO="kahnwong/swissknife"
GITHUB="https://api.github.com"
VERSION=`
  curl --silent "${GITHUB}/repos/{$REPO}/releases/latest" |
      grep '"tag_name":' |
      sed -E 's/.*"([^"]+)".*/\1/'
`
VERSION_BINARY=$(echo "${VERSION}" | sed 's/^v//')
BINARY_NAME="swissknife"
FILE="${BINARY_NAME}_${VERSION_BINARY}_${OS}_${ARCH}.tar.gz"

# get current path, will be used later
CURRENT_PATH=$(pwd)

# download
curl -L -s -o "/tmp/$FILE" "https://github.com/${REPO}/releases/download/${VERSION}/${FILE}"

# extract
echo "Extracting ${FILE}..."
cd "/tmp" || exit 1
tar -xzvf "${FILE}"
if [ $? -ne 0 ]; then
    echo "Error: Failed to extract ${FILE}."
    exit 1
fi

# cleanup
rm -f "${FILE}"
rm README.md

# move binary to CURRENT_PATH
mv "$BINARY_NAME" "${CURRENT_PATH}/"

# success message
echo "Successfully downloaded and extracted ${FILE}."
